baseURL = "https://fivetwentythree.github.io/exp/"
canonifyURLs = false                               # Forces all URLs to be absolute with baseURL
languageCode = 'en-us'
title = 'Lochana Perera'
[params]
description = "A thoughtful exploration of philosophy, ethics, and modern life through classical wisdom"
keywords = "philosophy, ethics, virtue, wisdom, blog"
author = "Lochana Perera"
# Add this to your hugo.toml file

[params.social]
twitter = "YourTwitterHandle" # Your Twitter/X username (without the @)
# You can add more here later, like:
github = "fivetwentythree"
